name: RISC-V Toolchain Test

on:
  workflow_dispatch:
    inputs:
      is_vector:
        required: true
        type: boolean
        default: false

jobs:
  run-RISCV_toolchain-test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Clone RISCV toolchain submodule
        run: |
          export CKPTFLOW_HOME=$(pwd)
          git submodule update --init artifacts/riscv-gnu-toolchain
          cd artifacts/riscv-gnu-toolchain
          git rm pk
          git rm qemu
          git rm spike
          git submodule update --init --recursive
          
      - name: Build RISCV toolchain submodule
        run: |
          # 编译命令
          if [ "${{ github.event.inputs.is_vector }}" = "true" ]; then
            echo "Configure with vector support"
            mkdir $CKPTFLOW_HOME/riscv-toolchain-build-vector
            ./configure --prefix=$CKPTFLOW_HOME/riscv-toolchain-build-vector --with-abi=lp64d --with-arch=rv64gcv
          else
            echo "Configure without vector support"
            mkdir $CKPTFLOW_HOME/riscv-toolchain-build-scalar
            ./configure --prefix=$CKPTFLOW_HOME/riscv-toolchain-build-scalar --with-abi=lp64d --with-arch=rv64gc
          fi
          make linux -j > build.log 2>&1
      - name: Enable jemalloc
        run: |
          git submodule update --init artifacts/CPU2006LiteWrapper
          if [ "${{ github.event.inputs.is_vector }}" = "true" ]; then
            export RISCV=$CKPTFLOW_HOME/riscv-toolchain-build-scalar
          else
            export RISCV=$CKPTFLOW_HOME/riscv-toolchain-build-scalar
          fi
          git clone https://github.com/jemalloc/jemalloc.git
          cd jemalloc
          cp $CKPTFLOW_HOME/artifacts/CPU2006LiteWrapper/jemalloc_cpp.patch ./
          git checkout -b apply-patch da66aa391f853ccf2300845b3873cc8f1cf48f2d
          git apply jemalloc_cpp.patch
          CC=$RISCV/bin/riscv64-unknown-linux-gnu-gcc CXX=$RISCV/bin/riscv64-unknown-linux-gnu-c++ LD=$RISCV/bin/riscv64-unknown-linux-gnu-ld ./autogen.sh --prefix=$RISCV --host=x86_64-linux-gnu
          make && make install